import numpy as np

configfile: "config.yml"

rule all:
    input:
        expand("{project}/{figure}", project = config["project"], figure = config["figures"]),
        # expand(
        #     "output/{project}/conductance_ltp/{idx}/{conductance}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 20),
        #     conductance = [ format(i, ".6f") for i in np.arange(0.00005, 0.0001 + 0.000005, 0.000005) ]
        # ),
        # expand(
        #     "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 20),
        #     conductance = ["0.000060", "0.000070"] # [ format(i, ".6f") for i in np.arange(0.00005, 0.0001 + 0.000005, 0.000005) ]
        # ),
        expand(
            "output/{project}/subthreshold_conductance2/{idx}.txt",
            project = config["project"],
            idx = np.array([x for x in np.arange(0, 21) if x != 3])
        ),
        expand(
            "output/{project}/{type}/{idx}/synapse_info.csv",
            project = config["project"],
            type = [
                "subthreshold_conductance_ltp_trace2",
                "subthreshold_conductance_ltp_trace_5Hz2",
                "subthreshold_conductance_ltp_trace_130Hz2",
                "subthreshold_conductance_ltp_trace_5Hz_9000"
            ],
            idx = np.array([x for x in np.arange(0, 21) if x != 3])
        )
        # expand(
        #     "output/{project}/ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 50),
        #     carrier = 0
        # ),
        # expand(
        #     "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 50),
        #     carrier = 1000,
        #     phi = 90,
        #     psi = 90,
        #     offset = [5, 130]
        # ),
        # expand(
        #     "output/{project}/poisson/{idx}/no_ti/{carrier}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 10),
        #     carrier = 0
        # ),
        # expand(
        #     "output/{project}/poisson/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 10),
        #     carrier = 1000,
        #     phi = 90,
        #     psi = 90,
        #     offset = [5, 130]
        # ),
        # expand(
        #     "output/{project}/poisson_theta/{idx}/no_ti/{carrier}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 30),
        #     carrier = 0
        # ),
        # expand(
        #     "output/{project}/poisson_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 30),
        #     carrier = 1000,
        #     phi = 90,
        #     psi = 90,
        #     offset = [5, 130]
        # ),
        # expand(
        #     "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 10),
        #     carrier = 1000,
        #     phi = 90,
        #     psi = 90,
        #     offset = [5],
        #     delay = [0, 25, 50, 75, 100, 125, 150, 175]
        # )
        # expand(
        #     "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 17),
        #     carrier = 0
        # ),
        # expand(
        #     "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        #     project = config["project"],
        #     idx = np.arange(0, 17),
        #     carrier = 1000,
        #     phi = 90,
        #     psi = 90,
        #     offset = [5, 130]
        # ),

rule neuron_model:
    output:
        png = "{project}/neuron_model.png"
    conda: "neuron"
    script: "figures/neuron_model.py"

rule neuron_model_with_synapses:
    output:
        png = "{project}/neuron_model_with_synapses.png"
    conda: "neuron"
    script: "figures/neuron_model_with_synapses.py"

rule generate_seeds:
    output:
        seeds = "output/{project}/seeds.csv"
    params:
        initial_seed = 42,
        n = 50
    conda: "neuron"
    script: "python/generate_seeds.py"

rule subthreshold_ef_strength:
    output:
        subthreshold = "output/{project}/ef/{angle_phi}_{angle_psi}_{carrier}.csv"
    params:
        offset_range = np.concatenate([[0], [0.5], np.arange(1, 10, 1), np.arange(10, 50, 5), np.arange(50, 140, 10)]),
        phase = 10,
        duration = 500,
        initial_amplitude = 1000,
        accuracy = 0.5
    conda: "neuron"
    script: "python/subthreshold_ef_strength.py"

rule ltp:
    input:
        seeds = "output/{project}/seeds.csv",
        subthreshold = "output/{project}/ef/{phi}_{psi}_{carrier}.csv"
    output:
        synapse_info = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        spike_frequency = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/spike_frequency.csv",
        voltage = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/voltage.csv",
        synapse_weights = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_weights.csv"
    params:
        n_synapses = 10,
        initial_conductance = 0.0001,
        duration = 2000, # ms
        ltp_duration = 1000, # ms
        ltp_frequency = 100, # Hz
        ef_strength = 0.9 # fraction of subthreshold amplitude
    conda: "neuron"
    script: "python/ltp.py"

rule ltp_no_ef:
    input:
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        spike_frequency = "output/{project}/ltp/{idx}/no_ti/{carrier}/spike_frequency.csv",
        voltage = "output/{project}/ltp/{idx}/no_ti/{carrier}/voltage.csv",
        synapse_weights = "output/{project}/ltp/{idx}/no_ti/{carrier}/synapse_weights.csv"
    params:
        n_synapses = 10,
        initial_conductance = 0.0001,
        duration = 2000, # ms
        ltp_duration = 1000, # ms
        ltp_frequency = 100 # Hz
    conda: "neuron"
    script: "python/ltp.py"

rule poisson:
    input:
        synapse_info = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        seeds = "output/{project}/seeds.csv",
        subthreshold = "output/{project}/ef/{phi}_{psi}_{carrier}.csv"
    output:
        synapse_info = "output/{project}/poisson/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson/{idx}/{carrier}/{phi}_{psi}_{offset}/spike_frequency.csv",
        voltage = "output/{project}/poisson/{idx}/{carrier}/{phi}_{psi}_{offset}/voltage.csv",
        synapse_weights = "output/{project}/poisson/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_weights.csv"
    params:
        duration = 5 * 60 * 1000, # ms, 5 minutes
        rate = 5, # Hz, poisson rate
        ef_strength = 0.9 # fraction of subthreshold amplitude
    conda: "neuron"
    script: "python/poisson.py"

rule poisson_no_ef:
    input:
        synapse_info = "output/{project}/ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/poisson/{idx}/no_ti/{carrier}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson/{idx}/no_ti/{carrier}/spike_frequency.csv",
        voltage = "output/{project}/poisson/{idx}/no_ti/{carrier}/voltage.csv",
        synapse_weights = "output/{project}/poisson/{idx}/no_ti/{carrier}/synapse_weights.csv"
    params:
        duration = 5 * 60 * 1000, # ms, 5 minutes
        rate = 5 # Hz, poisson rate
    conda: "neuron"
    script: "python/poisson.py"

rule poisson_theta:
    input:
        synapse_info = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        seeds = "output/{project}/seeds.csv",
        subthreshold = "output/{project}/ef/{phi}_{psi}_{carrier}.csv"
    output:
        synapse_info = "output/{project}/poisson_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/spike_frequency.csv",
        voltage = "output/{project}/poisson_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/voltage.csv",
        synapse_weights = "output/{project}/poisson_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_weights.csv"
    params:
        duration = 1 * 60 * 1000, # ms, 1 minute
        rate = 5, # Hz, poisson rate
        ef_strength = 0.9, # fraction of subthreshold amplitude
        burst_duration = 50,
        rate_in_burst = 100, # firing frequency during bursting interval
        rate_outside_burst = 1 # firing frequency outside bursting interval
    conda: "neuron"
    script: "python/poisson_in_frequency.py"

rule poisson_theta_delay:
    input:
        synapse_info = "output/{project}/ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        seeds = "output/{project}/seeds.csv",
        subthreshold = "output/{project}/ef/{phi}_{psi}_{carrier}.csv"
    output:
        synapse_info = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/spike_frequency.csv",
        voltage = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/voltage.csv",
        synapse_weights = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/synapse_weights.csv",
        synapse_voltage = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/synapse_voltage.csv",
        synapse_stimuli = "output/{project}/poisson_delay_theta/{idx}/{carrier}/{phi}_{psi}_{offset}/{delay}/synapse_stimuli.csv"
    params:
        duration = 1 * 60 * 1000, # ms, 1 minute
        rate = 5, # Hz, poisson rate
        ef_strength = 0.9, # fraction of subthreshold amplitude
        burst_duration = 50,
        rate_in_burst = 100, # firing frequency during bursting interval
        rate_outside_burst = 1 # firing frequency outside bursting interval
    conda: "neuron"
    script: "python/poisson_in_frequency_delay.py"

rule poisson_theta_no_ef:
    input:
        synapse_info = "output/{project}/ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/poisson_theta/{idx}/no_ti/{carrier}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson_theta/{idx}/no_ti/{carrier}/spike_frequency.csv",
        voltage = "output/{project}/poisson_theta/{idx}/no_ti/{carrier}/voltage.csv",
        synapse_weights = "output/{project}/poisson_theta/{idx}/no_ti/{carrier}/synapse_weights.csv"
    params:
        duration = 1 * 60 * 1000, # ms, 1 minute
        rate = 5, # Hz, poisson rate
        burst_duration = 50,
        rate_in_burst = 100, # firing frequency during bursting interval
        rate_outside_burst = 1 # firing frequency outside bursting interval
    conda: "neuron"
    script: "python/poisson_in_frequency.py"

rule poisson_theta_no_ltp:
    input:
        seeds = "output/{project}/seeds.csv",
        subthreshold = "output/{project}/ef/{phi}_{psi}_{carrier}.csv"
    output:
        synapse_info = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/spike_frequency.csv",
        voltage = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/voltage.csv",
        # synapse_weights = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_weights.csv",
        synapse_voltage = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_voltage.csv",
        synapse_stimuli = "output/{project}/poisson_theta_no_ltp/{idx}/{carrier}/{phi}_{psi}_{offset}/synapse_stimuli.csv"
    params:
        duration = 0.25 * 60 * 1000, # ms, 1 minute
        rate = 5, # Hz, poisson rate
        ef_strength = 0.9, # fraction of subthreshold amplitude
        burst_duration = 50,
        rate_in_burst = 100, # firing frequency during bursting interval
        rate_outside_burst = 1, # firing frequency outside bursting interval
        n_synapses = 1,
        initial_conductance = 0.0001
    conda: "neuron"
    script: "python/poisson_in_frequency_no_ltp.py"

rule poisson_theta_no_ltp_no_ef:
    input:
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/synapse_info.csv",
        spike_frequency = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/spike_frequency.csv",
        voltage = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/voltage.csv",
        # synapse_weights = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/synapse_weights.csv",
        synapse_voltage = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/synapse_voltage.csv",
        synapse_stimuli = "output/{project}/poisson_theta_no_ltp/{idx}/no_ti/{carrier}/synapse_stimuli.csv"
    params:
        duration = 0.25 * 60 * 1000, # ms, 1 minute
        rate = 5, # Hz, poisson rate
        ef_strength = 0.9, # fraction of subthreshold amplitude
        burst_duration = 50,
        rate_in_burst = 100, # firing frequency during bursting interval
        rate_outside_burst = 1, # firing frequency outside bursting interval
        n_synapses = 1,
        initial_conductance = 0.0001
    conda: "neuron"
    script: "python/poisson_in_frequency_no_ltp.py"

rule conductance_ltp:
    input:
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/conductance_ltp/{idx}/{conductance}/synapse_info.csv",
        spike_frequency = "output/{project}/conductance_ltp/{idx}/{conductance}/spike_frequency.csv",
        voltage = "output/{project}/conductance_ltp/{idx}/{conductance}/voltage.csv",
        synapse_weights = "output/{project}/conductance_ltp/{idx}/{conductance}/synapse_weights.csv",
        synapse_voltage = "output/{project}/conductance_ltp/{idx}/{conductance}/synapse_voltage.csv",
        synapse_stimuli = "output/{project}/conductance_ltp/{idx}/{conductance}/synapse_stimuli.csv"
    params:
        n_synapses = 10,
        initial_weight = 0.1,

        duration = 3000, # ms
        ltp_start = 1000, # ms
        ltp_duration = 1000, # ms
        ltp_frequency = 100, # Hz
        test_stim_times = [100, 2500] # ms
    conda: "neuron"
    script: "python/conductance_ltp.py"

rule conductance_ltp_ef:
    input:
        seeds = "output/{project}/seeds.csv"
    output:
        synapse_info = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/synapse_info.csv",
        spike_frequency = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/spike_frequency.csv",
        voltage = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/voltage.csv",
        synapse_weights = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/synapse_weights.csv",
        synapse_voltage = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/synapse_voltage.csv",
        synapse_stimuli = "output/{project}/conductance_ltp_ef_5/{idx}/{conductance}/synapse_stimuli.csv"
    params:
        n_synapses = 10,
        initial_weight = 0.1,

        duration = 3000, # ms
        ltp_start = 1000, # ms
        ltp_duration = 1000, # ms
        ltp_frequency = 100, # Hz
        test_stim_times = [100, 2500] # ms
    conda: "neuron"
    script: "python/conductance_ltp_ef.py"
